name: 'Dependabot Check for Vulnerabilities'
on:
  schedule:
    - cron: '0 15 * * 1-5' #UTC  todo: change once it's proven to work
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: check out current repositories
        # to read maintainers.json
        uses: actions/checkout@v4
      - name: check out cove-workflows
        # this is necessary because this workflow gets synced to other repos
        uses: actions/checkout@v4
        with:
          repository: livelyhood/cove-workflows
          ref: ${{ (github.repository == 'livelyhood/cove-workflows' && github.ref) || 'main' }} # IF the this workflow was called from this repo THEN checkout the current github.ref ELSE use main
          path: ./cove-workflows
          token: ${{ github.token }}
      - name: read maintainers.json
        id: read-maintainers
        # reads maintainers array and map them to their slack userIds "mentions" (see slack api https://api.slack.com/reference/surfaces/formatting#mentioning-users)
        run: |
          # shellcheck disable=SC2002
          echo "maintainers=$(cat maintainers.json | jq '.[] | to_entries | .[].value' | jq --slurp -r '. | join(" ")')" >> "$GITHUB_OUTPUT"
      - name: query open vulnerability alerts
        id: list-vulnerabilities
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const script = require('./cove-workflows/src/scripts/dependabot-open-vulnerabilities.js');
            return await script({github, context, core});
      - name: count open vulnerability alerts
        id: count-vulnerabilities
        env:
          VULNERABILITIES: ${{ steps.list-vulnerabilities.outputs.result }}
        run: |
          COUNT=$(echo "${VULNERABILITIES}" | jq '. | length')
          echo "count=${COUNT}" >> "${GITHUB_OUTPUT}"
      - name: Print vulnerability count
        if: ${{ steps.count-vulnerabilities.outputs.count > 0 }}
        run: echo "Found ${{ steps.count-vulnerabilities.outputs.count }} open vulnerabilities"
